# Generated by Django 3.2.8 on 2022-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='productName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
