# Generated by Django 3.2.8 on 2022-03-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_auto_20220307_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='print',
            new_name='price',
        ),
    ]
